#!/usr/bin/env bash
# Displays numbers from 1 to 20
# on 4th iteration display 'bad luck from china'
# on 9th iteration display 'bad luck from japan'
# on 17th iteration display 'bad luck from italy'

count=1

while [ $count -le 20 ]
do
        echo "$count"
        case $count in
		"4") echo "bad luck from china"
		;;
		"9") echo "bad luck from japan"
		;;
		"17") echo "bad luck from italy"
		;;
	esac
	(( count++ ))
done
