#!/usr/bin/env bash
# Run Nginx as Nginx. Fix in 7 lines or less

pkill apache
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chmod -R 777 /etc/nginx/
sudo -u nginx service nginx start
